spring:
  elasticsearch:
    rest:
      uris: ${re-url}:9200
      connection-timeout: 30s
      read-timeout: 30s
  rabbitmq:
    host: ${re-url}
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/baf?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      connection-test-query: SELECT 1
      initialization-fail-timeout: 0
  redis:
    host: ${mmr-url}
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
    timeout: 3000ms
    connect-timeout: 3000ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

email:
  config:
    from: "短趣视频"
    password: EYRxmzT4S6vjXUHh
    host: smtp.163.com
    port: 465
    user: 13414800914@163.com
    expire-time: 300
jwt:
  secret: OASNDASINQWMEAOSCNK
  expiration: 86400000
  issuer: lytoyo

minio:
  endpoint: http://${mmr-url}:9000
  bucketName: baf
  accessKey: JdV9xYmjrCkimUNjbdTa
  secretKey: GsxgzgVlDfa2OoXJxdEQvtPhjP9awNiLL8XFLRzt
  secure: false
  url: http://${minio-url}:9000/baf/

ffmpeg:
  path: /root/middleware/ffmpeg/ffmpeg-git-amd64/ffmpeg

mmr-url: 127.0.0.1

minio-url: 115.191.63.22

re-url: 106.12.132.206


